version: '3.8'

services:
  server:
    container_name: serverR
    image: nginx:alpine
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  php:
    container_name: phpR
    build: .
    ports:
      - "4565:9000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
